---
- name: Install Python RPM dependencies
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: "{{ python_dep_packages }}"
  tags:
    - python-libs
    - python-libs2
    - python-libs3

- name: Uninstall pycurl
  pip:
    name: pycurl
    executable: "{{ python_pip_bin }}"
    state: absent
  when: install_python and update_pycurl
  tags:
    - python-libs

- name: Reinstall pycurl with correct SSL lib
  shell: 'PYCURL_SSL_LIBRARY=nss {{ python_pip_bin }} install pycurl --global-option="--with-nss"'
  when: install_python and update_pycurl
  tags:
    - python-libs

- name: Update pip
  pip:
    name: "{{ item }}"
    executable: "{{ python_pip_bin }}"
    state: latest
  when: install_python
  with_items:
    - pip
    - setuptools
  tags:
    - python-libs

- name: Install Python packages for 27
  pip:
    name: "{{ python_packages }}"
    state: "{{ python_package_mode }}"
    executable: "{{ python_pip_bin }}"
  when: install_python
  tags:
    - python-libs
    - python-libs2

- name: Update pip
  pip:
    name: "{{ item }}"
    executable: "{{ python3_pip_bin }}"
    state: latest
  when: install_python
  with_items:
    - pip
    - setuptools
  tags:
    - python-libs

- name: Install Python packages for 35
  pip:
    name: "{{ python3_packages }}"
    state: "{{ python_package_mode }}"
    executable: "{{ python3_pip_bin }}"
  when: install_python
  tags:
    - python-libs
    - python-libs3
